services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: mataycode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  mataycode-api:
    container_name: mataycode-api
    image: matayyy/mataycode-website
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customer
    ports:
        - "8088:8080"
    networks:
        - postgres
    depends_on:
        - postgres
    restart: unless-stopped

  mataycode-react:
    container_name: mataycode-react
    image: matayyy/mataycode-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - mataycode-api
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres: