spring:
  application:
    name: mataycode-website

  datasource:
      url: jdbc:postgresql://localhost:5432/customer
      username: mataycode
      password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB


server:
  port: 8080
#  CONSIDER TURNING OFF ERROR MESSAGES TO PREVENT FROM LEAKING INFORMATION
  error:
    include-message: always

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

management:
  endpoints:
    web:
      exposure:
        include: "health, info"


aws:
  region: "eu-central-1"
  s3:
#    change to false to use real s3
    mock: true
    buckets:
      customer: mataycode-website-customer