aws:
  s3:
    mock: false

spring:
  datasource:
    url: jdbc:postgresql://awseb-e-2yx5iw9muc-stack-awsebrdsdatabase-e54czkdszcds.cbywrgbkjz1t.eu-central-1.rds.amazonaws.com:5432/ebdb
    username: mataycode
    password: password